#!/bin/torch_grid_dropout
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 0.5 --dropout 0 > ../log/dimension_100margin_0.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 0.5 --dropout 0.25 > ../log/dimension_100margin_0.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 0.5 --dropout 0.5 > ../log/dimension_100margin_0.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 0.5 --dropout 0.75 > ../log/dimension_100margin_0.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 0.5 --dropout 1.0 > ../log/dimension_100margin_0.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 1.0 --dropout 0 > ../log/dimension_100margin_1.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 1.0 --dropout 0.25 > ../log/dimension_100margin_1.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 1.0 --dropout 0.5 > ../log/dimension_100margin_1.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 1.0 --dropout 0.75 > ../log/dimension_100margin_1.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 1.0 --dropout 1.0 > ../log/dimension_100margin_1.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 1.5 --dropout 0 > ../log/dimension_100margin_1.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 1.5 --dropout 0.25 > ../log/dimension_100margin_1.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 1.5 --dropout 0.5 > ../log/dimension_100margin_1.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 1.5 --dropout 0.75 > ../log/dimension_100margin_1.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 1.5 --dropout 1.0 > ../log/dimension_100margin_1.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 2.0 --dropout 0 > ../log/dimension_100margin_2.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 2.0 --dropout 0.25 > ../log/dimension_100margin_2.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 2.0 --dropout 0.5 > ../log/dimension_100margin_2.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 2.0 --dropout 0.75 > ../log/dimension_100margin_2.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 2.0 --dropout 1.0 > ../log/dimension_100margin_2.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 2.5 --dropout 0 > ../log/dimension_100margin_2.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 2.5 --dropout 0.25 > ../log/dimension_100margin_2.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 2.5 --dropout 0.5 > ../log/dimension_100margin_2.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 2.5 --dropout 0.75 > ../log/dimension_100margin_2.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 2.5 --dropout 1.0 > ../log/dimension_100margin_2.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 3.0 --dropout 0 > ../log/dimension_100margin_3.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 3.0 --dropout 0.25 > ../log/dimension_100margin_3.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 3.0 --dropout 0.5 > ../log/dimension_100margin_3.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 3.0 --dropout 0.75 > ../log/dimension_100margin_3.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 3.0 --dropout 1.0 > ../log/dimension_100margin_3.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 3.5 --dropout 0 > ../log/dimension_100margin_3.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 3.5 --dropout 0.25 > ../log/dimension_100margin_3.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 3.5 --dropout 0.5 > ../log/dimension_100margin_3.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 3.5 --dropout 0.75 > ../log/dimension_100margin_3.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 3.5 --dropout 1.0 > ../log/dimension_100margin_3.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 4.0 --dropout 0 > ../log/dimension_100margin_4.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 4.0 --dropout 0.25 > ../log/dimension_100margin_4.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 4.0 --dropout 0.5 > ../log/dimension_100margin_4.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 4.0 --dropout 0.75 > ../log/dimension_100margin_4.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 4.0 --dropout 1.0 > ../log/dimension_100margin_4.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 4.5 --dropout 0 > ../log/dimension_100margin_4.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 4.5 --dropout 0.25 > ../log/dimension_100margin_4.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 4.5 --dropout 0.5 > ../log/dimension_100margin_4.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 4.5 --dropout 0.75 > ../log/dimension_100margin_4.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 4.5 --dropout 1.0 > ../log/dimension_100margin_4.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 5.0 --dropout 0 > ../log/dimension_100margin_5.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 5.0 --dropout 0.25 > ../log/dimension_100margin_5.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 5.0 --dropout 0.5 > ../log/dimension_100margin_5.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 5.0 --dropout 0.75 > ../log/dimension_100margin_5.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 100 --margin 5.0 --dropout 1.0 > ../log/dimension_100margin_5.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 0.5 --dropout 0 > ../log/dimension_200margin_0.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 0.5 --dropout 0.25 > ../log/dimension_200margin_0.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 0.5 --dropout 0.5 > ../log/dimension_200margin_0.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 0.5 --dropout 0.75 > ../log/dimension_200margin_0.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 0.5 --dropout 1.0 > ../log/dimension_200margin_0.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 1.0 --dropout 0 > ../log/dimension_200margin_1.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 1.0 --dropout 0.25 > ../log/dimension_200margin_1.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 1.0 --dropout 0.5 > ../log/dimension_200margin_1.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 1.0 --dropout 0.75 > ../log/dimension_200margin_1.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 1.0 --dropout 1.0 > ../log/dimension_200margin_1.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 1.5 --dropout 0 > ../log/dimension_200margin_1.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 1.5 --dropout 0.25 > ../log/dimension_200margin_1.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 1.5 --dropout 0.5 > ../log/dimension_200margin_1.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 1.5 --dropout 0.75 > ../log/dimension_200margin_1.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 1.5 --dropout 1.0 > ../log/dimension_200margin_1.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 2.0 --dropout 0 > ../log/dimension_200margin_2.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 2.0 --dropout 0.25 > ../log/dimension_200margin_2.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 2.0 --dropout 0.5 > ../log/dimension_200margin_2.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 2.0 --dropout 0.75 > ../log/dimension_200margin_2.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 2.0 --dropout 1.0 > ../log/dimension_200margin_2.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 2.5 --dropout 0 > ../log/dimension_200margin_2.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 2.5 --dropout 0.25 > ../log/dimension_200margin_2.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 2.5 --dropout 0.5 > ../log/dimension_200margin_2.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 2.5 --dropout 0.75 > ../log/dimension_200margin_2.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 2.5 --dropout 1.0 > ../log/dimension_200margin_2.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 3.0 --dropout 0 > ../log/dimension_200margin_3.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 3.0 --dropout 0.25 > ../log/dimension_200margin_3.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 3.0 --dropout 0.5 > ../log/dimension_200margin_3.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 3.0 --dropout 0.75 > ../log/dimension_200margin_3.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 3.0 --dropout 1.0 > ../log/dimension_200margin_3.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 3.5 --dropout 0 > ../log/dimension_200margin_3.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 3.5 --dropout 0.25 > ../log/dimension_200margin_3.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 3.5 --dropout 0.5 > ../log/dimension_200margin_3.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 3.5 --dropout 0.75 > ../log/dimension_200margin_3.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 3.5 --dropout 1.0 > ../log/dimension_200margin_3.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 4.0 --dropout 0 > ../log/dimension_200margin_4.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 4.0 --dropout 0.25 > ../log/dimension_200margin_4.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 4.0 --dropout 0.5 > ../log/dimension_200margin_4.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 4.0 --dropout 0.75 > ../log/dimension_200margin_4.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 4.0 --dropout 1.0 > ../log/dimension_200margin_4.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 4.5 --dropout 0 > ../log/dimension_200margin_4.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 4.5 --dropout 0.25 > ../log/dimension_200margin_4.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 4.5 --dropout 0.5 > ../log/dimension_200margin_4.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 4.5 --dropout 0.75 > ../log/dimension_200margin_4.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 4.5 --dropout 1.0 > ../log/dimension_200margin_4.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 5.0 --dropout 0 > ../log/dimension_200margin_5.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 5.0 --dropout 0.25 > ../log/dimension_200margin_5.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 5.0 --dropout 0.5 > ../log/dimension_200margin_5.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 5.0 --dropout 0.75 > ../log/dimension_200margin_5.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 200 --margin 5.0 --dropout 1.0 > ../log/dimension_200margin_5.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 0.5 --dropout 0 > ../log/dimension_300margin_0.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 0.5 --dropout 0.25 > ../log/dimension_300margin_0.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 0.5 --dropout 0.5 > ../log/dimension_300margin_0.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 0.5 --dropout 0.75 > ../log/dimension_300margin_0.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 0.5 --dropout 1.0 > ../log/dimension_300margin_0.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 1.0 --dropout 0 > ../log/dimension_300margin_1.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 1.0 --dropout 0.25 > ../log/dimension_300margin_1.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 1.0 --dropout 0.5 > ../log/dimension_300margin_1.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 1.0 --dropout 0.75 > ../log/dimension_300margin_1.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 1.0 --dropout 1.0 > ../log/dimension_300margin_1.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 1.5 --dropout 0 > ../log/dimension_300margin_1.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 1.5 --dropout 0.25 > ../log/dimension_300margin_1.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 1.5 --dropout 0.5 > ../log/dimension_300margin_1.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 1.5 --dropout 0.75 > ../log/dimension_300margin_1.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 1.5 --dropout 1.0 > ../log/dimension_300margin_1.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 2.0 --dropout 0 > ../log/dimension_300margin_2.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 2.0 --dropout 0.25 > ../log/dimension_300margin_2.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 2.0 --dropout 0.5 > ../log/dimension_300margin_2.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 2.0 --dropout 0.75 > ../log/dimension_300margin_2.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 2.0 --dropout 1.0 > ../log/dimension_300margin_2.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 2.5 --dropout 0 > ../log/dimension_300margin_2.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 2.5 --dropout 0.25 > ../log/dimension_300margin_2.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 2.5 --dropout 0.5 > ../log/dimension_300margin_2.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 2.5 --dropout 0.75 > ../log/dimension_300margin_2.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 2.5 --dropout 1.0 > ../log/dimension_300margin_2.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 3.0 --dropout 0 > ../log/dimension_300margin_3.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 3.0 --dropout 0.25 > ../log/dimension_300margin_3.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 3.0 --dropout 0.5 > ../log/dimension_300margin_3.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 3.0 --dropout 0.75 > ../log/dimension_300margin_3.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 3.0 --dropout 1.0 > ../log/dimension_300margin_3.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 3.5 --dropout 0 > ../log/dimension_300margin_3.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 3.5 --dropout 0.25 > ../log/dimension_300margin_3.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 3.5 --dropout 0.5 > ../log/dimension_300margin_3.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 3.5 --dropout 0.75 > ../log/dimension_300margin_3.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 3.5 --dropout 1.0 > ../log/dimension_300margin_3.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 4.0 --dropout 0 > ../log/dimension_300margin_4.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 4.0 --dropout 0.25 > ../log/dimension_300margin_4.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 4.0 --dropout 0.5 > ../log/dimension_300margin_4.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 4.0 --dropout 0.75 > ../log/dimension_300margin_4.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 4.0 --dropout 1.0 > ../log/dimension_300margin_4.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 4.5 --dropout 0 > ../log/dimension_300margin_4.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 4.5 --dropout 0.25 > ../log/dimension_300margin_4.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 4.5 --dropout 0.5 > ../log/dimension_300margin_4.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 4.5 --dropout 0.75 > ../log/dimension_300margin_4.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 4.5 --dropout 1.0 > ../log/dimension_300margin_4.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 5.0 --dropout 0 > ../log/dimension_300margin_5.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 5.0 --dropout 0.25 > ../log/dimension_300margin_5.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 5.0 --dropout 0.5 > ../log/dimension_300margin_5.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 5.0 --dropout 0.75 > ../log/dimension_300margin_5.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 300 --margin 5.0 --dropout 1.0 > ../log/dimension_300margin_5.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 0.5 --dropout 0 > ../log/dimension_400margin_0.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 0.5 --dropout 0.25 > ../log/dimension_400margin_0.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 0.5 --dropout 0.5 > ../log/dimension_400margin_0.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 0.5 --dropout 0.75 > ../log/dimension_400margin_0.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 0.5 --dropout 1.0 > ../log/dimension_400margin_0.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 1.0 --dropout 0 > ../log/dimension_400margin_1.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 1.0 --dropout 0.25 > ../log/dimension_400margin_1.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 1.0 --dropout 0.5 > ../log/dimension_400margin_1.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 1.0 --dropout 0.75 > ../log/dimension_400margin_1.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 1.0 --dropout 1.0 > ../log/dimension_400margin_1.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 1.5 --dropout 0 > ../log/dimension_400margin_1.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 1.5 --dropout 0.25 > ../log/dimension_400margin_1.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 1.5 --dropout 0.5 > ../log/dimension_400margin_1.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 1.5 --dropout 0.75 > ../log/dimension_400margin_1.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 1.5 --dropout 1.0 > ../log/dimension_400margin_1.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 2.0 --dropout 0 > ../log/dimension_400margin_2.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 2.0 --dropout 0.25 > ../log/dimension_400margin_2.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 2.0 --dropout 0.5 > ../log/dimension_400margin_2.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 2.0 --dropout 0.75 > ../log/dimension_400margin_2.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 2.0 --dropout 1.0 > ../log/dimension_400margin_2.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 2.5 --dropout 0 > ../log/dimension_400margin_2.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 2.5 --dropout 0.25 > ../log/dimension_400margin_2.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 2.5 --dropout 0.5 > ../log/dimension_400margin_2.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 2.5 --dropout 0.75 > ../log/dimension_400margin_2.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 2.5 --dropout 1.0 > ../log/dimension_400margin_2.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 3.0 --dropout 0 > ../log/dimension_400margin_3.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 3.0 --dropout 0.25 > ../log/dimension_400margin_3.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 3.0 --dropout 0.5 > ../log/dimension_400margin_3.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 3.0 --dropout 0.75 > ../log/dimension_400margin_3.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 3.0 --dropout 1.0 > ../log/dimension_400margin_3.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 3.5 --dropout 0 > ../log/dimension_400margin_3.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 3.5 --dropout 0.25 > ../log/dimension_400margin_3.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 3.5 --dropout 0.5 > ../log/dimension_400margin_3.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 3.5 --dropout 0.75 > ../log/dimension_400margin_3.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 3.5 --dropout 1.0 > ../log/dimension_400margin_3.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 4.0 --dropout 0 > ../log/dimension_400margin_4.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 4.0 --dropout 0.25 > ../log/dimension_400margin_4.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 4.0 --dropout 0.5 > ../log/dimension_400margin_4.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 4.0 --dropout 0.75 > ../log/dimension_400margin_4.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 4.0 --dropout 1.0 > ../log/dimension_400margin_4.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 4.5 --dropout 0 > ../log/dimension_400margin_4.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 4.5 --dropout 0.25 > ../log/dimension_400margin_4.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 4.5 --dropout 0.5 > ../log/dimension_400margin_4.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 4.5 --dropout 0.75 > ../log/dimension_400margin_4.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 4.5 --dropout 1.0 > ../log/dimension_400margin_4.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 5.0 --dropout 0 > ../log/dimension_400margin_5.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 5.0 --dropout 0.25 > ../log/dimension_400margin_5.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 5.0 --dropout 0.5 > ../log/dimension_400margin_5.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 5.0 --dropout 0.75 > ../log/dimension_400margin_5.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 400 --margin 5.0 --dropout 1.0 > ../log/dimension_400margin_5.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 0.5 --dropout 0 > ../log/dimension_500margin_0.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 0.5 --dropout 0.25 > ../log/dimension_500margin_0.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 0.5 --dropout 0.5 > ../log/dimension_500margin_0.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 0.5 --dropout 0.75 > ../log/dimension_500margin_0.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 0.5 --dropout 1.0 > ../log/dimension_500margin_0.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 1.0 --dropout 0 > ../log/dimension_500margin_1.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 1.0 --dropout 0.25 > ../log/dimension_500margin_1.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 1.0 --dropout 0.5 > ../log/dimension_500margin_1.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 1.0 --dropout 0.75 > ../log/dimension_500margin_1.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 1.0 --dropout 1.0 > ../log/dimension_500margin_1.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 1.5 --dropout 0 > ../log/dimension_500margin_1.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 1.5 --dropout 0.25 > ../log/dimension_500margin_1.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 1.5 --dropout 0.5 > ../log/dimension_500margin_1.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 1.5 --dropout 0.75 > ../log/dimension_500margin_1.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 1.5 --dropout 1.0 > ../log/dimension_500margin_1.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 2.0 --dropout 0 > ../log/dimension_500margin_2.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 2.0 --dropout 0.25 > ../log/dimension_500margin_2.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 2.0 --dropout 0.5 > ../log/dimension_500margin_2.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 2.0 --dropout 0.75 > ../log/dimension_500margin_2.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 2.0 --dropout 1.0 > ../log/dimension_500margin_2.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 2.5 --dropout 0 > ../log/dimension_500margin_2.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 2.5 --dropout 0.25 > ../log/dimension_500margin_2.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 2.5 --dropout 0.5 > ../log/dimension_500margin_2.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 2.5 --dropout 0.75 > ../log/dimension_500margin_2.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 2.5 --dropout 1.0 > ../log/dimension_500margin_2.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 3.0 --dropout 0 > ../log/dimension_500margin_3.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 3.0 --dropout 0.25 > ../log/dimension_500margin_3.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 3.0 --dropout 0.5 > ../log/dimension_500margin_3.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 3.0 --dropout 0.75 > ../log/dimension_500margin_3.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 3.0 --dropout 1.0 > ../log/dimension_500margin_3.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 3.5 --dropout 0 > ../log/dimension_500margin_3.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 3.5 --dropout 0.25 > ../log/dimension_500margin_3.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 3.5 --dropout 0.5 > ../log/dimension_500margin_3.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 3.5 --dropout 0.75 > ../log/dimension_500margin_3.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 3.5 --dropout 1.0 > ../log/dimension_500margin_3.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 4.0 --dropout 0 > ../log/dimension_500margin_4.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 4.0 --dropout 0.25 > ../log/dimension_500margin_4.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 4.0 --dropout 0.5 > ../log/dimension_500margin_4.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 4.0 --dropout 0.75 > ../log/dimension_500margin_4.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 4.0 --dropout 1.0 > ../log/dimension_500margin_4.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 4.5 --dropout 0 > ../log/dimension_500margin_4.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 4.5 --dropout 0.25 > ../log/dimension_500margin_4.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 4.5 --dropout 0.5 > ../log/dimension_500margin_4.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 4.5 --dropout 0.75 > ../log/dimension_500margin_4.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 4.5 --dropout 1.0 > ../log/dimension_500margin_4.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 5.0 --dropout 0 > ../log/dimension_500margin_5.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 5.0 --dropout 0.25 > ../log/dimension_500margin_5.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 5.0 --dropout 0.5 > ../log/dimension_500margin_5.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 5.0 --dropout 0.75 > ../log/dimension_500margin_5.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 500 --margin 5.0 --dropout 1.0 > ../log/dimension_500margin_5.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 0.5 --dropout 0 > ../log/dimension_600margin_0.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 0.5 --dropout 0.25 > ../log/dimension_600margin_0.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 0.5 --dropout 0.5 > ../log/dimension_600margin_0.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 0.5 --dropout 0.75 > ../log/dimension_600margin_0.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 0.5 --dropout 1.0 > ../log/dimension_600margin_0.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 1.0 --dropout 0 > ../log/dimension_600margin_1.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 1.0 --dropout 0.25 > ../log/dimension_600margin_1.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 1.0 --dropout 0.5 > ../log/dimension_600margin_1.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 1.0 --dropout 0.75 > ../log/dimension_600margin_1.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 1.0 --dropout 1.0 > ../log/dimension_600margin_1.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 1.5 --dropout 0 > ../log/dimension_600margin_1.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 1.5 --dropout 0.25 > ../log/dimension_600margin_1.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 1.5 --dropout 0.5 > ../log/dimension_600margin_1.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 1.5 --dropout 0.75 > ../log/dimension_600margin_1.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 1.5 --dropout 1.0 > ../log/dimension_600margin_1.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 2.0 --dropout 0 > ../log/dimension_600margin_2.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 2.0 --dropout 0.25 > ../log/dimension_600margin_2.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 2.0 --dropout 0.5 > ../log/dimension_600margin_2.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 2.0 --dropout 0.75 > ../log/dimension_600margin_2.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 2.0 --dropout 1.0 > ../log/dimension_600margin_2.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 2.5 --dropout 0 > ../log/dimension_600margin_2.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 2.5 --dropout 0.25 > ../log/dimension_600margin_2.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 2.5 --dropout 0.5 > ../log/dimension_600margin_2.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 2.5 --dropout 0.75 > ../log/dimension_600margin_2.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 2.5 --dropout 1.0 > ../log/dimension_600margin_2.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 3.0 --dropout 0 > ../log/dimension_600margin_3.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 3.0 --dropout 0.25 > ../log/dimension_600margin_3.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 3.0 --dropout 0.5 > ../log/dimension_600margin_3.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 3.0 --dropout 0.75 > ../log/dimension_600margin_3.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 3.0 --dropout 1.0 > ../log/dimension_600margin_3.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 3.5 --dropout 0 > ../log/dimension_600margin_3.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 3.5 --dropout 0.25 > ../log/dimension_600margin_3.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 3.5 --dropout 0.5 > ../log/dimension_600margin_3.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 3.5 --dropout 0.75 > ../log/dimension_600margin_3.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 3.5 --dropout 1.0 > ../log/dimension_600margin_3.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 4.0 --dropout 0 > ../log/dimension_600margin_4.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 4.0 --dropout 0.25 > ../log/dimension_600margin_4.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 4.0 --dropout 0.5 > ../log/dimension_600margin_4.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 4.0 --dropout 0.75 > ../log/dimension_600margin_4.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 4.0 --dropout 1.0 > ../log/dimension_600margin_4.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 4.5 --dropout 0 > ../log/dimension_600margin_4.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 4.5 --dropout 0.25 > ../log/dimension_600margin_4.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 4.5 --dropout 0.5 > ../log/dimension_600margin_4.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 4.5 --dropout 0.75 > ../log/dimension_600margin_4.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 4.5 --dropout 1.0 > ../log/dimension_600margin_4.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 5.0 --dropout 0 > ../log/dimension_600margin_5.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 5.0 --dropout 0.25 > ../log/dimension_600margin_5.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 5.0 --dropout 0.5 > ../log/dimension_600margin_5.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 5.0 --dropout 0.75 > ../log/dimension_600margin_5.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 600 --margin 5.0 --dropout 1.0 > ../log/dimension_600margin_5.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 0.5 --dropout 0 > ../log/dimension_700margin_0.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 0.5 --dropout 0.25 > ../log/dimension_700margin_0.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 0.5 --dropout 0.5 > ../log/dimension_700margin_0.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 0.5 --dropout 0.75 > ../log/dimension_700margin_0.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 0.5 --dropout 1.0 > ../log/dimension_700margin_0.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 1.0 --dropout 0 > ../log/dimension_700margin_1.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 1.0 --dropout 0.25 > ../log/dimension_700margin_1.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 1.0 --dropout 0.5 > ../log/dimension_700margin_1.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 1.0 --dropout 0.75 > ../log/dimension_700margin_1.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 1.0 --dropout 1.0 > ../log/dimension_700margin_1.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 1.5 --dropout 0 > ../log/dimension_700margin_1.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 1.5 --dropout 0.25 > ../log/dimension_700margin_1.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 1.5 --dropout 0.5 > ../log/dimension_700margin_1.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 1.5 --dropout 0.75 > ../log/dimension_700margin_1.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 1.5 --dropout 1.0 > ../log/dimension_700margin_1.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 2.0 --dropout 0 > ../log/dimension_700margin_2.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 2.0 --dropout 0.25 > ../log/dimension_700margin_2.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 2.0 --dropout 0.5 > ../log/dimension_700margin_2.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 2.0 --dropout 0.75 > ../log/dimension_700margin_2.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 2.0 --dropout 1.0 > ../log/dimension_700margin_2.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 2.5 --dropout 0 > ../log/dimension_700margin_2.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 2.5 --dropout 0.25 > ../log/dimension_700margin_2.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 2.5 --dropout 0.5 > ../log/dimension_700margin_2.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 2.5 --dropout 0.75 > ../log/dimension_700margin_2.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 2.5 --dropout 1.0 > ../log/dimension_700margin_2.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 3.0 --dropout 0 > ../log/dimension_700margin_3.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 3.0 --dropout 0.25 > ../log/dimension_700margin_3.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 3.0 --dropout 0.5 > ../log/dimension_700margin_3.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 3.0 --dropout 0.75 > ../log/dimension_700margin_3.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 3.0 --dropout 1.0 > ../log/dimension_700margin_3.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 3.5 --dropout 0 > ../log/dimension_700margin_3.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 3.5 --dropout 0.25 > ../log/dimension_700margin_3.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 3.5 --dropout 0.5 > ../log/dimension_700margin_3.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 3.5 --dropout 0.75 > ../log/dimension_700margin_3.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 3.5 --dropout 1.0 > ../log/dimension_700margin_3.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 4.0 --dropout 0 > ../log/dimension_700margin_4.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 4.0 --dropout 0.25 > ../log/dimension_700margin_4.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 4.0 --dropout 0.5 > ../log/dimension_700margin_4.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 4.0 --dropout 0.75 > ../log/dimension_700margin_4.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 4.0 --dropout 1.0 > ../log/dimension_700margin_4.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 4.5 --dropout 0 > ../log/dimension_700margin_4.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 4.5 --dropout 0.25 > ../log/dimension_700margin_4.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 4.5 --dropout 0.5 > ../log/dimension_700margin_4.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 4.5 --dropout 0.75 > ../log/dimension_700margin_4.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 4.5 --dropout 1.0 > ../log/dimension_700margin_4.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 5.0 --dropout 0 > ../log/dimension_700margin_5.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 5.0 --dropout 0.25 > ../log/dimension_700margin_5.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 5.0 --dropout 0.5 > ../log/dimension_700margin_5.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 5.0 --dropout 0.75 > ../log/dimension_700margin_5.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 700 --margin 5.0 --dropout 1.0 > ../log/dimension_700margin_5.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 0.5 --dropout 0 > ../log/dimension_800margin_0.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 0.5 --dropout 0.25 > ../log/dimension_800margin_0.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 0.5 --dropout 0.5 > ../log/dimension_800margin_0.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 0.5 --dropout 0.75 > ../log/dimension_800margin_0.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 0.5 --dropout 1.0 > ../log/dimension_800margin_0.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 1.0 --dropout 0 > ../log/dimension_800margin_1.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 1.0 --dropout 0.25 > ../log/dimension_800margin_1.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 1.0 --dropout 0.5 > ../log/dimension_800margin_1.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 1.0 --dropout 0.75 > ../log/dimension_800margin_1.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 1.0 --dropout 1.0 > ../log/dimension_800margin_1.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 1.5 --dropout 0 > ../log/dimension_800margin_1.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 1.5 --dropout 0.25 > ../log/dimension_800margin_1.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 1.5 --dropout 0.5 > ../log/dimension_800margin_1.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 1.5 --dropout 0.75 > ../log/dimension_800margin_1.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 1.5 --dropout 1.0 > ../log/dimension_800margin_1.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 2.0 --dropout 0 > ../log/dimension_800margin_2.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 2.0 --dropout 0.25 > ../log/dimension_800margin_2.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 2.0 --dropout 0.5 > ../log/dimension_800margin_2.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 2.0 --dropout 0.75 > ../log/dimension_800margin_2.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 2.0 --dropout 1.0 > ../log/dimension_800margin_2.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 2.5 --dropout 0 > ../log/dimension_800margin_2.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 2.5 --dropout 0.25 > ../log/dimension_800margin_2.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 2.5 --dropout 0.5 > ../log/dimension_800margin_2.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 2.5 --dropout 0.75 > ../log/dimension_800margin_2.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 2.5 --dropout 1.0 > ../log/dimension_800margin_2.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 3.0 --dropout 0 > ../log/dimension_800margin_3.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 3.0 --dropout 0.25 > ../log/dimension_800margin_3.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 3.0 --dropout 0.5 > ../log/dimension_800margin_3.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 3.0 --dropout 0.75 > ../log/dimension_800margin_3.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 3.0 --dropout 1.0 > ../log/dimension_800margin_3.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 3.5 --dropout 0 > ../log/dimension_800margin_3.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 3.5 --dropout 0.25 > ../log/dimension_800margin_3.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 3.5 --dropout 0.5 > ../log/dimension_800margin_3.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 3.5 --dropout 0.75 > ../log/dimension_800margin_3.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 3.5 --dropout 1.0 > ../log/dimension_800margin_3.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 4.0 --dropout 0 > ../log/dimension_800margin_4.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 4.0 --dropout 0.25 > ../log/dimension_800margin_4.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 4.0 --dropout 0.5 > ../log/dimension_800margin_4.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 4.0 --dropout 0.75 > ../log/dimension_800margin_4.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 4.0 --dropout 1.0 > ../log/dimension_800margin_4.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 4.5 --dropout 0 > ../log/dimension_800margin_4.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 4.5 --dropout 0.25 > ../log/dimension_800margin_4.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 4.5 --dropout 0.5 > ../log/dimension_800margin_4.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 4.5 --dropout 0.75 > ../log/dimension_800margin_4.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 4.5 --dropout 1.0 > ../log/dimension_800margin_4.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 5.0 --dropout 0 > ../log/dimension_800margin_5.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 5.0 --dropout 0.25 > ../log/dimension_800margin_5.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 5.0 --dropout 0.5 > ../log/dimension_800margin_5.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 5.0 --dropout 0.75 > ../log/dimension_800margin_5.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 800 --margin 5.0 --dropout 1.0 > ../log/dimension_800margin_5.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 0.5 --dropout 0 > ../log/dimension_900margin_0.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 0.5 --dropout 0.25 > ../log/dimension_900margin_0.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 0.5 --dropout 0.5 > ../log/dimension_900margin_0.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 0.5 --dropout 0.75 > ../log/dimension_900margin_0.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 0.5 --dropout 1.0 > ../log/dimension_900margin_0.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 1.0 --dropout 0 > ../log/dimension_900margin_1.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 1.0 --dropout 0.25 > ../log/dimension_900margin_1.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 1.0 --dropout 0.5 > ../log/dimension_900margin_1.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 1.0 --dropout 0.75 > ../log/dimension_900margin_1.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 1.0 --dropout 1.0 > ../log/dimension_900margin_1.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 1.5 --dropout 0 > ../log/dimension_900margin_1.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 1.5 --dropout 0.25 > ../log/dimension_900margin_1.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 1.5 --dropout 0.5 > ../log/dimension_900margin_1.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 1.5 --dropout 0.75 > ../log/dimension_900margin_1.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 1.5 --dropout 1.0 > ../log/dimension_900margin_1.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 2.0 --dropout 0 > ../log/dimension_900margin_2.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 2.0 --dropout 0.25 > ../log/dimension_900margin_2.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 2.0 --dropout 0.5 > ../log/dimension_900margin_2.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 2.0 --dropout 0.75 > ../log/dimension_900margin_2.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 2.0 --dropout 1.0 > ../log/dimension_900margin_2.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 2.5 --dropout 0 > ../log/dimension_900margin_2.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 2.5 --dropout 0.25 > ../log/dimension_900margin_2.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 2.5 --dropout 0.5 > ../log/dimension_900margin_2.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 2.5 --dropout 0.75 > ../log/dimension_900margin_2.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 2.5 --dropout 1.0 > ../log/dimension_900margin_2.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 3.0 --dropout 0 > ../log/dimension_900margin_3.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 3.0 --dropout 0.25 > ../log/dimension_900margin_3.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 3.0 --dropout 0.5 > ../log/dimension_900margin_3.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 3.0 --dropout 0.75 > ../log/dimension_900margin_3.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 3.0 --dropout 1.0 > ../log/dimension_900margin_3.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 3.5 --dropout 0 > ../log/dimension_900margin_3.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 3.5 --dropout 0.25 > ../log/dimension_900margin_3.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 3.5 --dropout 0.5 > ../log/dimension_900margin_3.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 3.5 --dropout 0.75 > ../log/dimension_900margin_3.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 3.5 --dropout 1.0 > ../log/dimension_900margin_3.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 4.0 --dropout 0 > ../log/dimension_900margin_4.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 4.0 --dropout 0.25 > ../log/dimension_900margin_4.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 4.0 --dropout 0.5 > ../log/dimension_900margin_4.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 4.0 --dropout 0.75 > ../log/dimension_900margin_4.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 4.0 --dropout 1.0 > ../log/dimension_900margin_4.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 4.5 --dropout 0 > ../log/dimension_900margin_4.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 4.5 --dropout 0.25 > ../log/dimension_900margin_4.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 4.5 --dropout 0.5 > ../log/dimension_900margin_4.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 4.5 --dropout 0.75 > ../log/dimension_900margin_4.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 4.5 --dropout 1.0 > ../log/dimension_900margin_4.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 5.0 --dropout 0 > ../log/dimension_900margin_5.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 5.0 --dropout 0.25 > ../log/dimension_900margin_5.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 5.0 --dropout 0.5 > ../log/dimension_900margin_5.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 5.0 --dropout 0.75 > ../log/dimension_900margin_5.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 900 --margin 5.0 --dropout 1.0 > ../log/dimension_900margin_5.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 0.5 --dropout 0 > ../log/dimension_1000margin_0.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 0.5 --dropout 0.25 > ../log/dimension_1000margin_0.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 0.5 --dropout 0.5 > ../log/dimension_1000margin_0.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 0.5 --dropout 0.75 > ../log/dimension_1000margin_0.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 0.5 --dropout 1.0 > ../log/dimension_1000margin_0.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 1.0 --dropout 0 > ../log/dimension_1000margin_1.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 1.0 --dropout 0.25 > ../log/dimension_1000margin_1.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 1.0 --dropout 0.5 > ../log/dimension_1000margin_1.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 1.0 --dropout 0.75 > ../log/dimension_1000margin_1.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 1.0 --dropout 1.0 > ../log/dimension_1000margin_1.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 1.5 --dropout 0 > ../log/dimension_1000margin_1.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 1.5 --dropout 0.25 > ../log/dimension_1000margin_1.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 1.5 --dropout 0.5 > ../log/dimension_1000margin_1.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 1.5 --dropout 0.75 > ../log/dimension_1000margin_1.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 1.5 --dropout 1.0 > ../log/dimension_1000margin_1.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 2.0 --dropout 0 > ../log/dimension_1000margin_2.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 2.0 --dropout 0.25 > ../log/dimension_1000margin_2.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 2.0 --dropout 0.5 > ../log/dimension_1000margin_2.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 2.0 --dropout 0.75 > ../log/dimension_1000margin_2.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 2.0 --dropout 1.0 > ../log/dimension_1000margin_2.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 2.5 --dropout 0 > ../log/dimension_1000margin_2.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 2.5 --dropout 0.25 > ../log/dimension_1000margin_2.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 2.5 --dropout 0.5 > ../log/dimension_1000margin_2.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 2.5 --dropout 0.75 > ../log/dimension_1000margin_2.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 2.5 --dropout 1.0 > ../log/dimension_1000margin_2.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 3.0 --dropout 0 > ../log/dimension_1000margin_3.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 3.0 --dropout 0.25 > ../log/dimension_1000margin_3.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 3.0 --dropout 0.5 > ../log/dimension_1000margin_3.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 3.0 --dropout 0.75 > ../log/dimension_1000margin_3.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 3.0 --dropout 1.0 > ../log/dimension_1000margin_3.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 3.5 --dropout 0 > ../log/dimension_1000margin_3.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 3.5 --dropout 0.25 > ../log/dimension_1000margin_3.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 3.5 --dropout 0.5 > ../log/dimension_1000margin_3.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 3.5 --dropout 0.75 > ../log/dimension_1000margin_3.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 3.5 --dropout 1.0 > ../log/dimension_1000margin_3.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 4.0 --dropout 0 > ../log/dimension_1000margin_4.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 4.0 --dropout 0.25 > ../log/dimension_1000margin_4.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 4.0 --dropout 0.5 > ../log/dimension_1000margin_4.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 4.0 --dropout 0.75 > ../log/dimension_1000margin_4.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 4.0 --dropout 1.0 > ../log/dimension_1000margin_4.0dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 4.5 --dropout 0 > ../log/dimension_1000margin_4.5dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 4.5 --dropout 0.25 > ../log/dimension_1000margin_4.5dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 4.5 --dropout 0.5 > ../log/dimension_1000margin_4.5dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 4.5 --dropout 0.75 > ../log/dimension_1000margin_4.5dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 4.5 --dropout 1.0 > ../log/dimension_1000margin_4.5dropout_1.0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 5.0 --dropout 0 > ../log/dimension_1000margin_5.0dropout_0.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 5.0 --dropout 0.25 > ../log/dimension_1000margin_5.0dropout_0.25.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 5.0 --dropout 0.5 > ../log/dimension_1000margin_5.0dropout_0.5.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 5.0 --dropout 0.75 > ../log/dimension_1000margin_5.0dropout_0.75.txt
cd /share/project/zuyao/src && . ~/torch_env/env.sh && th train2_multi.lua --dimension 1000 --margin 5.0 --dropout 1.0 > ../log/dimension_1000margin_5.0dropout_1.0.txt
